orbs:
  slack: circleci/slack@4.10.1

version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:16.13.0
  slack-executor:
    docker:
      - image: 'cibuilds/base:latest'
    resource_class: small

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - app-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "package.json" }}

  deploy:
    executor: default
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Build Project
          command: |
            npm install
            npm run build
            cd build
            zip ../build.zpi -r * .[^.]*
            echo "Build successful"
      - run:
          name: Deploy to FIrebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=${FIREBASE_TOKEN}
  notify-via-slack:
    executor: slack-executor
    steps:
      - run: echo "Slack notification"
      - slack/notify:
          event: 'always'
          channel: C02R8V82XDH
          template: 'basic_success_1'

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - notify-via-slack:
          requires:
            - deploy
          filters:
            branches:
              only: master