orbs:
  slack: circleci/slack@4.10.1
  cypress: cypress-io/cypress@2.2.0
version: 2.1
executors:
  cypress-docker:
    docker:
      - image: 'shotaromatsuya/cypress-base:16'
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node:16.13.0
  slack-executor:
    docker:
      - image: 'cibuilds/base:latest'
    resource_class: small
environment:
  TZ: '/usr/share/zoneinfo/Asia/Tokyo'
jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
            - npm-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-{{ checksum "package.json" }}
  linting:
    executor: default
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
            - npm-
      - run:
          name: Run linting
          command: npm run lint
  prettier:
    executor: default
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
            - npm-
      - run:
          name: Run prettier check
          command: npm run prettier:check
  test:
    executor: default
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
            - npm-
      - run:
          name: Run Component Test
          command: npm run test
  deploy:
    executor: default
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Build Project
          command: |
            npm install
            npm run build
            cd build
            zip ../build.zpi -r * .[^.]*
            echo "Build successful"
      - run:
          name: Deploy to FIrebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=${FIREBASE_TOKEN}
  notify-via-slack:
    executor: slack-executor
    steps:
      - run: echo "Slack notification"
      - slack/notify:
          event: 'always'
          channel: C02R8V82XDH
          template: 'basic_success_1'

workflows:
  build:
    jobs:
      - cypress/install:
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          filters:
            branches:
              only: master
      - cypress/run:
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          requires:
            - cypress/install
          filters:
            branches:
              only: master
          record: true
          parallel: true
          parallelism: 2
          group: 2 machines 
          executor: cypress-docker
          start: npm run start
          wait-on: 'http://localhost:3000'
      - notify-via-slack:
          requires:
            - cypress/run
          filters:
            branches:
              only:
                - master
